name: Build to GH Pages
on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: 3.x
                
            - name: build
              id: build
              run: |
                python3 -m pip install -r requirements.txt
                mkdocs build

            # TODO: once this is deployed to the real site, uncomment
            # - run: echo cmfive.com >> site/CNAME

            - name: Upload artifact
              id: deployment
              uses: actions/upload-pages-artifact@v3
              with:
                path: site/
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Deploy to pages
              id: deployment
              uses: actions/deploy-pages@v4